# SYNOPSIS
#   This playbook creates our standard set of service accounts for Linux servers.
# DESCRIPTION
#   This playbook checks for the existence of our standard set of service accounts for Linux
#   servers and creates them if missing.
# PARAMETER <Parameter_Name>
#   --extra-vars "svc_veeam_pass=*** svc_solarwinds_pass=*** svc_nessus_pass=***"
# INPUTS
#   None
# OUTPUTS
#   None
# NOTES
#   Updated by:     Barker, Griffeth (barkergriffeth@gmail.com)
#   Change Date:    2023-10-09
#   Purpose/Change: Initial development
#
#   Be sure to pass the service account passwords as variables. Replace with info from your secrets manager as appropriate.
# EXAMPLE
#   ansible-playbook create_linux_service_accounts.yml -i your_inventory.yml --extra-vars "svc_veeam_pass=*** svc_solarwinds_pass=*** svc_nessus_pass=***" -u your_user -b
---
- name: Create standard service accounts for Linux servers
  hosts: all
  gather_facts: false
  become: true

  # Declare variables specific to this playbook
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansbile_become_password: "changeme"

  # Execute actions
  tasks:
    # Create the service account for Veeam Backup and Replication
    - name: Create Veeam Backup and Replication service account
      ansible.builtin.user:
        name: svc_veeam
        password: "{{ svc_veeam_pass | password_hash('sha512', 'salt') }}"
        comment: svc_veeam
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    # Create the service account for SolarWinds Orion
    - name: Create SolarWinds Orion service account
      ansible.builtin.user:
        name: svc_solarwinds
        password: "{{ svc_solarwinds_pass | password_hash('sha512', 'salt') }}"
        comment: svc_solarwinds
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    # Create the service account for Nessus Professional/Tenable.io
    - name: Create Nessus Professional/Tenable.io service account
      ansible.builtin.user:
        name: svc_nessus
        password: "{{ svc_nessus_pass | password_hash('sha512', 'salt') }}"
        comment: svc_nessus
        shell: /bin/bash
        create_home: yes
        groups: sudo
        append: yes
        state: present

    # Optional push notification via ntfy.sh
    # This playbook was intended to be scheduled via Ansible Semaphore and so the
    # message to refer to the console for results is in reference to that. Because
    # it is more specific to my usage, I've left it commented out here.
    #- name: Send ntfy.sh push notification
    #  ansible.builtin.uri:
    #    url: https://ntfy.sh/changeme
    #    method: POST
    #    headers: 
    #      title: "☑️ Playbook completed a run"
    #    body: "The playbook to create the standard service accounts on Linux servers has completed a run. Please see the console for results."
...
